name: Deploy

on:
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  REMOTE_URI: github.com/I110IS/i110is.github.io.git
  REMOTE_NAME: pages
  BRANCH_NAME: gh-pages

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: npm
        run: npm install
      - name: Build
        run: ./build

      - name: Configure git
        run: |
          git remote add ${{ env.REMOTE_NAME }} https://${{ env.REMOTE_URL }}
          git config user.name "Deploy Bot"
          git config user.email "<>"

      - name: Timestamp
        id: timestamp
        run: echo "::set-output name=value::$(date +'%Y-%m-%dT%H:%M:%S')"

      - name: Commit & push
        run: |
          mv dist/ docs/
          git add docs
          git commit -m "${{ format('[Deploy] {0}', steps.timestamp.outputs.value) }}"
          git checkout -B ${{ env.BRANCH_NAME }}
          git push https://${{ secrets.DEPLOY_USERNAME }}:${{ secrets.DEPLOY_ACCESS_TOKEN }}@${{ env.REMOTE_URI }} -f
