name: Deploy

on:
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  DEPLOY_REMOTE_URI: github.com/I110IS/i110is.github.io.git
  DEPLOY_REMOTE_NAME: pages
  DEPLOY_REPO_NAME: i110is.github.io
  DEPLOY_BRANCH_NAME: gh-pages

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: npm
        run: npm install
      - name: Build
        run: ./build

      - name: Configure git
        run: |
          git config --global user.name "Deploy Bot"
          git config --global user.email "<>"
          git config user.name "Deploy Bot"
          git config user.email "<>"

      - name: Timestamp
        id: timestamp
        run: echo "::set-output name=value::$(date +'%Y-%m-%dT%H:%M:%S')"

      - name: Commit & push
        run: |
          cd ..
          git clone https://${{ secrets.DEPLOY_USERNAME }}:${{ secrets.DEPLOY_ACCESS_TOKEN }}@${{ env.DEPLOY_REMOTE_URI }} target
          mv labs/dist/ target/docs/
          cd target
          git add docs
          git commit -m "${{ format('[Deploy] {0}', steps.timestamp.outputs.value) }}"
          git push https://${{ secrets.DEPLOY_USERNAME }}:${{ secrets.DEPLOY_ACCESS_TOKEN }}@${{ env.DEPLOY_REMOTE_URI }} -f
